version: '3.8'
services:
  api-go:
    build: .
    container_name: cangas_api_go
    ports:
      - "8443:8443"
    volumes:
      - ./locales.json:/app/locales.json:ro
      - ./certs:/app/certs:ro
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
